#	\-\     /-/  .          .              . |--|
#	 \ \   / /   .   /----| .    / /--\ \  . |  |
#	  \ \ / /    .  /  ---| .   / /----\ \ . |  |
#	   \   /     . /  /     .   | |------| . |  |
#	   /   \     . \  \     .   | |        . |  |
#	  / / \ \    .  \  ---| .   \ \-----|  . |  |
#	 / /   \ \   .   \----| .    \------|  . |  |
#	/-/     \-\  .          .              . |--|
#	          Welcome to Xceled Ngine
#                   by Khinenw
#        "Convenient, Stable, yet Extendable"
#            "This project applies GPLv3"

name: "XcelNgien"
author: Khinenw
version: "erita [1.0]"
description: "Xceled Ngien for minigames"
main: org\Khinenw\xcel\XcelNgien
api: 1.12.0
depend: [GameCoreFramework, XcelUpdater]

permissions:
  xcel.*:
    description: "The permission for using xcel ngien features."
    default: op
    children:
      xcel.sgw:
        description: "The permission for setting a game level."
        default: op

commands:
  sgw:
    description: "Sets a game world."
    usage: "/sgw [Game Name] [World Folder Name]"
    permission: gcf.grank
